version: 2
updates:
  # Update dependencies in `requirements.txt`
  - package-ecosystem: "pip"
    directory: "/"  # Directory where requirements.txt is located
    schedule:
      interval: "weekly"  # Frequency of checks (daily, weekly, or monthly)

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
